

# start by pulling the python image
#FROM python:3.9.15-alpine
FROM --platform=linux/amd64 python:3.9.15-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

RUN pip install --upgrade pip
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

RUN python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.11.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["app.py" ]